# pipeline.yml

build-job:
  image: python:3.11
  script:
    - echo "Building application..."
    - apt-get update && apt-get install -y build-essential
    - python --version
    - pip install --quiet build
    - echo "Build complete!"